# Generated by Django 3.1.6 on 2021-04-08 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210408_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_follows_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='follower',
        ),
    ]
