# Generated by Django 3.1.6 on 2021-05-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksanalyser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Investing', 'Investing'), ('tech_analysis', 'tech_analysis'), ('fund_analysis', 'fund_analysis')], default='Investing', max_length=20),
        ),
    ]
